const c=window.CHANGE_UK_CONFIG||{},ok=c.SUPABASE_URL&&!c.SUPABASE_URL.includes('YOUR-PROJECT')&&c.SUPABASE_ANON_KEY&&!c.SUPABASE_ANON_KEY.includes('YOUR_PUBLIC'),sb=ok?supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY):null;const login=document.getElementById('adminLogin'),ui=document.getElementById('adminUI'),status=document.getElementById('aStatus');let policies=[];
async function isAdmin(user){if(!user)return false;const {data}=await sb.from('profiles').select('is_admin').eq('id',user.id).maybeSingle();return !!data?.is_admin}
async function route(session){if(!session||!(await isAdmin(session.user))){login.classList.remove('hidden');ui.classList.add('hidden');return}login.classList.add('hidden');ui.classList.remove('hidden');await loadAdmin()}
if(sb){sb.auth.getSession().then(({data})=>route(data.session));sb.auth.onAuthStateChange((_e,s)=>route(s))}else status.textContent='Configure Supabase in config.js first.';
aLogin.onclick=async()=>{if(!sb)return;status.textContent='Signing in…';const {data,error}=await sb.auth.signInWithPassword({email:aEmail.value,password:aPass.value});if(error){status.textContent=error.message;return}if(!(await isAdmin(data.user))){status.textContent='This account is not marked as an admin.';await sb.auth.signOut()}};aLogout.onclick=()=>sb?.auth.signOut();
async function loadAdmin(){const [{data:set},{data:pol}]=await Promise.all([sb.from('site_settings').select('*'),sb.from('policies').select('*').order('sort_order')]);const sm=set?.find(x=>x.key==='stats')?.value||{};sMps.value=sm.mps||0;sCouncillors.value=sm.councillors||0;sCouncils.value=sm.councils||0;sNotice.value=set?.find(x=>x.key==='hero_notice')?.value?.text||'';policies=pol||[];renderPolicies()}
saveStats.onclick=async()=>{await sb.from('site_settings').upsert([{key:'stats',value:{mps:+sMps.value||0,councillors:+sCouncillors.value||0,councils:+sCouncils.value||0}},{key:'hero_notice',value:{text:sNotice.value}}]);alert('Saved')};
function renderPolicies(){policyEditor.innerHTML=policies.map((p,i)=>`<div class="policy-edit" data-i="${i}"><div class="grid"><label>Title<input data-k="title" value="${esc(p.title)}"></label><label>Category<input data-k="category" value="${esc(p.category||'')}"></label><label>Order<input data-k="sort_order" type="number" value="${p.sort_order||i+1}"></label></div><label>Summary<textarea data-k="summary">${esc(p.summary||'')}</textarea></label><label>Full detail<textarea data-k="detail">${esc(p.detail||'')}</textarea></label><label>Quiz question<input data-k="quiz_question" value="${esc(p.quiz_question||'')}"></label><label>Manifesto answer on scale 1–5<select data-k="quiz_position">${[1,2,3,4,5].map(x=>`<option ${x==p.quiz_position?'selected':''}>${x}</option>`).join('')}</select></label><label><input data-k="published" type="checkbox" ${p.published?'checked':''}> Published</label><button class="btn primary" onclick="savePolicy(${i})">Save policy</button> <button class="btn danger" onclick="deletePolicy(${i})">Delete</button></div>`).join('')}
function esc(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
window.savePolicy=async i=>{const box=document.querySelector(`[data-i="${i}"]`),obj={};box.querySelectorAll('[data-k]').forEach(el=>obj[el.dataset.k]=el.type==='checkbox'?el.checked:el.dataset.k==='sort_order'||el.dataset.k==='quiz_position'?+el.value:el.value);if(policies[i]?.id)obj.id=policies[i].id;const {error}=await sb.from('policies').upsert(obj);if(error)alert(error.message);else{await loadAdmin();alert('Policy saved')}};window.deletePolicy=async i=>{if(!confirm('Delete this policy?'))return;await sb.from('policies').delete().eq('id',policies[i].id);await loadAdmin()};newPolicy.onclick=()=>{policies.push({title:'New policy',category:'Policy',summary:'',detail:'',quiz_question:'',quiz_position:3,published:false,sort_order:policies.length+1});renderPolicies()};publishNews.onclick=async()=>{const {error}=await sb.from('news').insert({title:nTitle.value,body:nBody.value,published:true,published_at:new Date().toISOString()});if(error)alert(error.message);else{nTitle.value='';nBody.value='';alert('Published')}};
